### ISSUE TITLE
[bug] conan promotion does not work in 2.21.0

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan-extensions#208]
### Describe the bug

```
version: 2.21.0
conan_path: /opt/venv/bin/conan
python
  version: 3.9.19
  sys_version: 3.9.19 (main, Aug 29 2024, 05:41:50) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)]
  sys_executable: /opt/venv/bin/python3
  is_frozen: False
  architecture: x86_64
system
  version: conan-io/conan#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025
  platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.28
  system: Linux
  release: 6.6.87.2-microsoft-standard-WSL2
  cpu: x86_64
```

### How to reproduce it

`conan art:promote uploaded.json --from="conan-packages-local" --to="conan-products-local" --server="artifactory"`

```python
ERROR: Traceback (most recent call last):
  File "/opt/venv/lib64/python3.9/site-packages/conan/cli/cli.py", line 297, in main
    cli.run(args)
  File "/opt/venv/lib64/python3.9/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/opt/venv/lib64/python3.9/site-packages/conan/cli/command.py", line 183, in run
    info = self._method(conan_api, parser, *args)
  File "/opt/conan/extensions/commands/art/cmd_promote.py", line 114, in promote
    for name_version, recipe in pkglist.recipes.items():
AttributeError: 'PackagesList' object has no attribute 'recipes'
ERROR: 'PackagesList' object has no attribute 'recipes'
```

Hello. I can't be sure it is linked, but the promotion of conan packages suddenly stopped working as soon as the client was updated to the `2.21.0` version on the company's CI. Could you please check it out? Thanks!

**Comment by memsharded** [comment]
Fixed in #209, please update and let us know

**Comment by Todiq** [comment]
Fixed! Thanks a lot!
